### ISSUE TITLE
Управление с руля в AA

### ISSUE THREAD

**Issue by dmgouriev** [delletenebre/Yamus#3]
Добрый день! Столкнулся с проблемой - в плейлисте, если на руле нажать "следующий трек" в режиме Android Auto, то произойдет переход и, не начиная воспроизведение, через пару секунд перескочет еще на следующий, который и воспроизведет. Т.е. по факту происходит скачек через трек. Можете что-нибудь подсказать по этому вопросу?

**Comment by iHeadRu** [comment]
Аналогично.

**Comment by delletenebre** [comment]
Добрый день. О проблеме знаю, разбираюсь в причинах.

**Comment by s0d2** [comment]
Ещё комментарий:
Если до этого музыка с телефона игралась через bt, то после подключения через AA не работает управление кнопками с руля.

**Comment by delletenebre** [comment]
Нашёл причину, исправил. Теперь треки должны нормально переключаться :)

**Comment by delletenebre** [comment]
> Ещё комментарий:
> Если до этого музыка с телефона игралась через bt, то после подключения через AA не работает управление кнопками с руля.

Что-то пропустил это, но тут подсказать пока ничего не могу. Надо будет найти руль с переключением треков. Если и дальше будет так, откройте новый issue.
