### ISSUE TITLE
Отображение плейлиста

### ISSUE THREAD

**Issue by s0d2** [delletenebre/Yamus#5]
Заметил следующее поведение. Если плейлист не помещается на двух экранах, то отображается не целиком. Чтобы листать дальше, нужно включить последний трек в отображаемой части плейлиста.

**Comment by delletenebre** [comment]
Не совсем понял в чём дело. Это в интерфейсе Android Auto или в приложении на телефоне?

**Comment by delletenebre** [comment]
Если я правильно понял проблему, то в версии от 19 января добавлена опция в настройках для интерфейса Android Auto: автоматический запуск или отображение треков при выборе плейлиста
