### ISSUE TITLE
Автоматическое воспроизведение треков

### ISSUE THREAD

**Issue by Nipochomus** [delletenebre/Yamus#9]
Здравствуйте, дико извиняюсь и прошу не бить ногами, но где включается автоматическое воспроизведение треков при выборе плейлиста в версии 20.01.2019?
![Screenshot_2020-03-13-19-58-22-858_kg delletenebre yamus](https://user-images.githubusercontent.com/12968200/76632525-2bd98780-6565-11ea-8feb-1c62ae2efd8c.jpg)
![Screenshot_2020-03-13-19-58-26-032_kg delletenebre yamus](https://user-images.githubusercontent.com/12968200/76632540-3136d200-6565-11ea-8213-fec35cc1044d.jpg)

Ещё заметил что при плохом соединении с интернетом может возникнуть ошибка воспроизведения, которая может исправить только заново выбрав мелодию, что не очень удобно в дороге.

В остальном великолепное приложение! Спасибо!

**Comment by delletenebre** [comment]
Здравствуйте. Если я правильно понял проблему, то раздел "Интерфейс Android Auto", выключить "Показывать треки в плейлистах". Согласен, не понятно :)

**Comment by Nipochomus** [comment]
Большое спасибо :)
